name: Run
on:
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * 1,2,3,4,5"
jobs:
  run:
    runs-on: ubuntu-latest
    name: Run

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run
        run: python main.py

      - name: Read Date Data
        id: read_date_data
        uses: ashley-taylor/read-json-property-action@v1.0
        with:
          path: data.json
          property: date

      - name: Read Fetched Zip Data
        id: read_fetched_zip_data
        uses: ashley-taylor/read-json-property-action@v1.0
        with:
          path: data.json
          property: fetched_zip_path

      - name: Read Release Body Data
        id: read_release_body_data
        uses: ashley-taylor/read-json-property-action@v1.0
        with:
          path: data.json
          property: release_body

      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.read_date_data.outputs.value }}
          release_name: ${{ steps.read_date_data.outputs.value }}
          body: ${{ steps.read_release_body_data.outputs.value }}
          draft: false
          prerelease: false

      - name: Upload Release Asset Fetched Zip File
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ steps.read_fetched_zip_data.outputs.value }}
          asset_name: ${{ steps.read_date_data.outputs.value }}.zip
          asset_content_type: application/zip
